services:
  api-rest:
    build:
      context: .
      dockerfile: api-rest/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped

  api-soap:
    build:
      context: .
      dockerfile: api-soap/Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
